<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_financier.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><?php echo $this->title_2; ?><br/>
	<div class="gd_titre">IV.LE DOSSIER FINANCIER</div>
	<div class="gd_titre">1. LES BESOINS DE FINANCEMENT</div>
	<div class="sous_titre">1.1. Besoin de financement global</div>
	<div class="sous_titre">1.2. Les demandes de financement</div>
	<div class="gd_titre">2. COMPOSITION DU DOSSIER FINANCIER</div>

	
	<div>
	<?php /* <input name="Modifier" onclick="window.location.href='<?php echo $this->url(array('controller'=>'redaction','action'=>'titre')); ?>'"  type="submit" class="button" value="Modifier les titres" /> */?>
	
	</div>
	
			
		
	</div>

