<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_projet.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><?php echo $this->title_2; ?><br/>
	<div class="gd_titre">II. LE PROJET</div>
	<div class="gd_titre">1. <?php echo $this->titreProjet->titre_1; ?></div>
	<div class="sous_titre">1.1. <?php echo $this->titreProjet->titre_1_1; ?></div>
	<div class="sous_titre">1.2. <?php echo $this->titreProjet->titre_1_2; ?></div>
	<div class="sous_titre">1.3. <?php echo $this->titreProjet->titre_1_3; ?></div>
	<div class="sous_titre">1.4. <?php echo $this->titreProjet->titre_1_4; ?></div>
	<div class="sous_titre">1.5. <?php echo $this->titreProjet->titre_1_5; ?></div>
	<div class="sous_titre">1.6. <?php echo $this->titreProjet->titre_1_6; ?></div>
	<div class="gd_titre">2. <?php echo $this->titreProjet->titre_2; ?></div>
	<div class="sous_titre">2.1. <?php echo $this->titreProjet->titre_2_1; ?></div>
	<div class="sous_titre">2.2. <?php echo $this->titreProjet->titre_2_2; ?></div>
	<div class="sous_titre">2.3. <?php echo $this->titreProjet->titre_2_3; ?></div>
	<div class="sous_titre">2.4. <?php echo $this->titreProjet->titre_2_4; ?></div>
	<div class="gd_titre">3. <?php echo $this->titreProjet->titre_3; ?></div>
	<div class="sous_titre">3.1. <?php echo $this->titreProjet->titre_3_1; ?></div>
	<div class="sous_titre">3.2. <?php echo $this->titreProjet->titre_3_2; ?></div>
	<div class="sous_titre">3.3. <?php echo $this->titreProjet->titre_3_3; ?></div>
	<div class="sous_titre">3.4. <?php echo $this->titreProjet->titre_3_4; ?></div>
	<div class="sous_titre">3.5. <?php echo $this->titreProjet->titre_3_5; ?></div>

	<div>
	<?php /* <input name="Modifier" onclick="window.location.href='<?php echo $this->url(array('controller'=>'redaction','action'=>'titre')); ?>'"  type="submit" class="button" value="Modifier les titres" /> */?>
	
	</div>
	
			
		
	</div>

