<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_aspect.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><?php echo $this->title_2; ?><br/>
	<div class="gd_titre">III.LES ASPECTS JURIDIQUES, FISCAUX et SOCIAUX</div>
	<div class="gd_titre">1. LES ASPECTS JURIDIQUES</div>
	<div class="gd_titre">2. LES ASPECTS FISCAUX</div>
	<div class="gd_titre">3. LES ASPECTS SOCIAUX</div>
	
	<div>
	<?php /* <input name="Modifier" onclick="window.location.href='<?php echo $this->url(array('controller'=>'redaction','action'=>'titre')); ?>'"  type="submit" class="button" value="Modifier les titres" /> */?>
	
	</div>
	
			
		
	</div>

