<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_aspect.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<?php echo $this->title_2; ?>
	<div>
<br/>
Prévoyez-vous de vous rémunérer dans le cadre de votre activité non salariée ?<br/>
Pourrez-vous déduire votre rémunération des charges de l’entreprise ?<br/>
Votre entreprise remplit-elle les conditions d'un dispositif d'exonération d'impôt (association, jeune entreprise innovante, ZUS, ZFU ZRU…) ?<br/>
Votre activité est-elle assujettie à la T.V.A. ?<br/>

<br/>







<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" >

	<?php echo $this->form->texte_titre_aspect_2; ?><br/>
	
	
	<center><?php echo $this->form->submit; ?></center>		</form>
	</div>

</div>