<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_presentation.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<?php echo $this->title_2; ?>
	<div>
<br/>
<h4>Origine de l’idée</h4>
Quelle est l’origine de votre idée ? L’idée vous vient-elle d’une expérience professionnelle, d’un savoir-faire, d’une opportunité, d’une passion, d’une reconversion… ?<br/>
Décrivez brièvement l’origine de votre idée afin de démontrer la pertinence de votre choix. (Vous devez convaincre votre interlocuteur que votre idée n’a pas été choisie par hasard)<br/>

<h4>Motivations et objectifs poursuivis</h4>
Qu’est ce qui vous motive à créer votre entreprise ?  Vous créé votre entreprise par souci d’indépendance, pour créer votre propre emploi, <br/>
Comment vous projetez-vous dans votre future activité? Souhaitez-vous uniquement créer votre propre emploi ou envisagez-vous créer des emplois<br/>



<br/>






<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" >

	<?php echo $this->form->texte_titre_presentation_2_2; ?><br/>
	
	
	<center><?php echo $this->form->submit; ?></center>		</form>
	</div>

</div>