<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_presentation.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<?php echo $this->title_2; ?>
	<div>
<br/>

<ul>
<li>2.4.1 <a  href="<?php  echo $this->baseUrl();?>/redaction/titrepresentation241/?div=div_2" ><?php echo $this->titrePresentation->titre_2_4_1; ?></a></li>	
<li>2.4.2 <a  href="<?php  echo $this->baseUrl();?>/redaction/titrepresentation242/?div=div_2" ><?php echo $this->titrePresentation->titre_2_4_2; ?></a></li>	
<li>2.4.3 <a  href="<?php  echo $this->baseUrl();?>/redaction/titrepresentation243/?div=div_2" ><?php echo $this->titrePresentation->titre_2_4_3; ?></a></li>	
			
</ul>



</div></div>