<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_projet.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<?php echo $this->title_2; ?>
	<div>
<br/>

Quelle est la clientèle cible ? (Particuliers, entreprises, administrations, collectivités locales)<br/>
Quel est le profil des différents clients potentiels visés ? (CSP, âge, sexe, situation maritale, tranches de revenus, budget annuel ou mensuel, habitudes de consommation..)<br/>
Votre clientèle est-elle diffuse ou concentrée sur une zone géographique ?<br/>
Que recherchent les clients potentiels visés ? Quels sont leurs besoins ? A quoi sont-ils sensibles ?<br/>
Quel est l'intérêt de l'offre pour les clients potentiels visés ?<br/>

<br/>







<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" >

	<?php echo $this->form->texte_titre_projet_1_3; ?><br/>
	
	
	<center><?php echo $this->form->submit; ?></center>		</form>
	</div>

</div>