<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_presentation.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<?php echo $this->title_2; ?>
	<div>
<br/>
<h4>Vos atouts</h4>
Quels sont vos atouts personnels pour réussir votre projet ? (rigueur, organisation, stable, bon relationnel, adaptation, tempérament commercial, capacité à manager, volonté de réalisation, ambition, dynamique, tenace…)
<br/>
<h4>Vos faiblesses</h4>
Connaissez-vous vos faiblesses ? (lacunes commerciales, difficultés en gestion, organisation, manque de réalisme, ambition démesurée, manque d’écoute…)
<br/>
<br/>






<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" >

	<?php echo $this->form->texte_titre_presentation_2_3; ?><br/>
	
	
	<center><?php echo $this->form->submit; ?></center>		</form>
	</div>

</div>