<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_projet.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<?php echo $this->title_2; ?>
	<div>
<br/>
Décrivez le mode de calcul de votre chiffre d’affaire a démarrage.<br/>
Décomposez votre CA selon le critère qui vous paraît le plus significatif. <br/>
Par exemple le nombre d’heures et le taux horaire ou le nombre de journées facturées, le nombre et le prix des produits ou services vendus, le taux des commissions, etc.
<br/>
Précisez les hypothèses retenues pour expliquer la croissance du CA sur les années 2 et 3.<br/>
Vos ventes doivent être estimées sur des hypothèses réalistes et tenir compte des périodes creuses (saisonnalité). <br/>
Le CA doit être estimé sur la base de 20 jours par mois ; 11 mois par an soit au total 220 jours travaillés au maximum.<br/>

<br/>






<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" >

	<?php echo $this->form->texte_titre_projet_2_4; ?><br/>
	
	
	<center><?php echo $this->form->submit; ?></center>		</form>
	</div>

</div>