<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_projet.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<?php echo $this->title_2; ?>
	<div>
<br/>

Avez-vous vérifié que votre produit/service correspond à un besoin réel ?<br/>
Votre produit ou service est un moyen permettant de répondre aux attentes et aux besoins de vos clients.<br/>

Si votre produit ne correspond à aucun besoin (attente ou désir) du consommateur il ne se vendra pas. Il n'a donc aucune raison d'exister.
<br/>
Avez-vous un produit ou une gamme, plusieurs produits ou plusieurs gammes ?<br/>
Si vous proposez vos produits ou services à plusieurs typologies de clients, vous devez impérativement les adapter aux attentes et aux besoins de ces derniers.
<br/>Exemples : 
<br/>- le libraire propose des ouvrages différents (sport, histoire, gastronomie) en fonction de ses clients,
<br/>- l'informaticien ne proposera pas les mêmes prestations et les mêmes tarifs aux entreprises et aux particuliers.
<br/>Comment traitez-vous les aspects suivants : conditionnement, marque commerciale ?

<br/>





<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" >

	<?php echo $this->form->texte_titre_projet_2_1; ?><br/>
	
	
	<center><?php echo $this->form->submit; ?></center>		</form>
	</div>

</div>