<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_financier.phtml'); ?>



	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
	<div class="titre_long">Trésorerie</div><br/>
	</div>

