<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_projet.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<?php echo $this->title_2; ?>
	<div>
<br/>

Pour chaque fournisseur, décrivez brièvement les produits achetés, les prix, les délais de livraison et les conditions de paiement.<br/>
Référez-vous au support méthodologique <br/>



<br/>







<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" >

	<?php echo $this->form->texte_titre_projet_1_5; ?><br/>
	
	
	<center><?php echo $this->form->submit; ?></center>		</form>
	</div>

</div>