<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_financier.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<ul>

<li>Plan de financement de départ et sur 3 ans</li>
<li>Compte de résultats prévisionnel sur 3 ans</li>
<li>Plan de trésorerie détaillée sur 12 mois</li>
<li>Détail du calcul du chiffre d’affaires</li>
<li>Calcul du seuil de rentabilité</li>
<li>Calcul du BFR (Besoin en Fonds de Roulement) sur 3 ans</li>
</ul>



	</div>

</div>