<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche.phtml'); ?>



	<div class="contenu_ac">
	<div class="titre_maj">
	<?php echo $this->title; ?><br/><br/>
	<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" ><table><tr><td><?php echo $this->form->titre_sommaire; ?></td><td></td></tr>
	<tr><td><?php echo $this->form->titre_intro; ?></td><td></td></tr>
	<tr><td>1. <?php echo $this->form->titre_1; ?></td><td></td></tr>
	<tr><td></td><td>1.1. <?php echo $this->form->titre_1_1; ?></td></tr>
	<tr><td></td><td>1.2. <?php echo $this->form->titre_1_2; ?></td></tr>
	<tr><td>2. <?php echo $this->form->titre_2; ?></td><td></td></tr>
	<tr><td></td><td>2.1. <?php echo $this->form->titre_2_1; ?></td></tr>
	<tr><td></td><td>2.2. <?php echo $this->form->titre_2_2; ?></td></tr>
	<tr><td></td><td>2.3. <?php echo $this->form->titre_2_3; ?></td></tr>
	<tr><td>3. <?php echo $this->form->titre_3; ?></td><td></td></tr>
	
	<tr><td></td><td>3.1. <?php echo $this->form->titre_3_1; ?></td></tr>
	<tr><td></td><td></td><td>3.1.1. <?php echo $this->form->titre_3_1_1; ?></td></tr>
	<tr><td></td><td></td><td>3.1.2. <?php echo $this->form->titre_3_1_2; ?></td></tr>
	<tr><td></td><td>3.2. <?php echo $this->form->titre_3_2; ?></td></tr>
	<tr><td></td><td></td><td>3.2.1. <?php echo $this->form->titre_3_2_1; ?></td></tr>
	<tr><td></td><td></td><td>3.2.2. <?php echo $this->form->titre_3_2_2; ?></td></tr>
	<tr><td></td><td></td><td>3.2.3. <?php echo $this->form->titre_3_2_3; ?></td></tr>
	
	<tr><td></td><td>3.3. <?php echo $this->form->titre_3_3; ?></td><td></td></tr>
	<tr><td></td><td></td><td>3.3.1. <?php echo $this->form->titre_3_3_1; ?></td></tr>
	<tr><td></td><td></td><td>3.3.2. <?php echo $this->form->titre_3_3_2; ?></td></tr>
	<tr><td></td><td></td><td>3.3.3. <?php echo $this->form->titre_3_3_3; ?></td></tr>
	<tr><td></td><td>3.4. <?php echo $this->form->titre_3_4; ?></td><td></td></tr>
	<tr><td>4. <?php echo $this->form->titre_4; ?></td><td></td></tr>
	<tr><td></td><td>4.1. <?php echo $this->form->titre_4_1; ?></td></tr>
	<tr><td></td><td>4.2. <?php echo $this->form->titre_4_2; ?></td></tr>
	<tr><td></td><td></td><td>4.2.1. <?php echo $this->form->titre_4_2_1; ?></td></tr>
	<tr><td></td><td></td><td>4.2.2. <?php echo $this->form->titre_4_2_2; ?></td></tr>
	<tr><td></td><td></td><td>4.2.3. <?php echo $this->form->titre_4_2_3; ?></td></tr>
	<tr><td></td><td></td><td>4.2.4. <?php echo $this->form->titre_4_2_4; ?></td></tr>
	<tr><td></td><td>4.3. <?php echo $this->form->titre_4_3; ?></td></tr>
	<tr><td></td><td></td><td>4.3.1. <?php echo $this->form->titre_4_3_1; ?></td></tr>
	<tr><td></td><td></td><td>4.3.2. <?php echo $this->form->titre_4_3_2; ?></td></tr>
	<tr><td></td><td></td><td>4.3.3. <?php echo $this->form->titre_4_3_3; ?></td></tr>
	<tr><td></td><td>4.4. <?php echo $this->form->titre_4_4; ?></td></tr>
	<tr><td></td><td></td><td>4.4.1. <?php echo $this->form->titre_4_4_1; ?></td></tr>
	<tr><td></td><td></td><td>4.4.2. <?php echo $this->form->titre_4_4_2; ?></td></tr>
	<tr><td></td><td></td><td>4.4.3. <?php echo $this->form->titre_4_4_3; ?></td></tr>
	<tr><td>5. <?php echo $this->form->titre_5; ?></td><td></td></tr>
	<tr><td>6. <?php echo $this->form->titre_6; ?></td><td></td></tr>
	<tr><td></td><td>6.1. <?php echo $this->form->titre_6_1; ?></td></tr>
	<tr><td></td><td>6.2. <?php echo $this->form->titre_6_2; ?></td></tr>
	<tr><td></td><td>6.3. <?php echo $this->form->titre_6_3; ?></td></tr>
	<tr><td>7. <?php echo $this->form->titre_7; ?></td><td></td></tr>
	<tr><td>8. <?php echo $this->form->titre_8; ?></td><td></td></tr>
	<tr><td>9. <?php echo $this->form->titre_9; ?></td><td></td></tr>
	
	
	</table> 
	<center><?php echo $this->form->submit; ?></center>		</form>
	</div></div></div>

