<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_financier.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<?php echo $this->title_2; ?>
	<div>
<br/><br/>Indiquez les montants des différentes sources de financement : prêt bancaire, prêt d’honneur, PCE, prêt NACRE. <br/>
Envisagez-vous une garantie France active (FAG, FGIF) ?<br/><br/>





<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" >

	<?php echo $this->form->texte_titre_financier_1_2; ?><br/>
	
	
	<center><?php echo $this->form->submit; ?></center>		</form>
	</div>

</div>