<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>

<?php echo $this->render('menu_gauche_projet.phtml'); ?>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<?php echo $this->title_2; ?>
	<div>
<br/>
Quels sont vos principaux moyens de communication (Site Internet, portfolio, plaquettes, cartes de visite, flyers, participation à des salons, presse locale, référencement, création de partenariats…)<br/>
Votre politique de communication doit s'inscrire dans un ensemble homogène et cohérent. <br/>
Exemple : si votre projet s’adresse essentiellement à une clientèle de proximité, vous devez privilégier des moyens de communication locaux (bulletin municipale, affiches chez les commerçants du quartier, panneaux d’affichage…) plutôt que d’envisager un média télévisé.<br/>
Votre communication ne doit pas être épisodique mais doit se faire de façon régulière. <br/>
Prévoyez ainsi un calendrier pour vos actions publicitaires et évaluez les coûts.

<br/>
<br/>





<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" >

	<?php echo $this->form->texte_titre_projet_2_3; ?><br/>
	
	
	<center><?php echo $this->form->submit; ?></center>		</form>
	</div>

</div>