
<h4><img alt="Fiche organisation" src="./images/ico/contact_box.png">
Coordonnées de l'organisation</h4>
<table>
	<tr>
		<td>Catégorie</td>
		<td><select id="categorie_org">
			<option value=""></option>
			<?php for($i=0;$i<count($this->listCategorie_org);$i++)
			{
				echo'<option value="'.$this->listCategorie_org[$i]['cat_id'].'">'.utf8_encode($this->listCategorie_org[$i]['cat_name']).'</option>';
			}?>
		</select></td>
	</tr>
	<tr>
		<td>Code organisme</td>
		<td><input id="code_organisme_org" type="text" /></td>
		<td>Code Naf</td>
		<td><input 
			name="code_naf_" id="code_naf_" type="text" />
		
		</div>
		</td>
	</tr>

	<tr>
		<td>Nom de l'organisme</td>
		<td><input id="id_organisation_org" type="hidden" /><input
			id="nom_organisme_org" type="text" /></td>
		<td>Activité principale</td>
		<td><input type="text" id="activite_principale_org" /></td>
	</tr>
	<tr>
		<td>Raison sociale</td>
		<td><input id="raison_sociale_org" type="text" /></td>
		<td>Type d'adresse</td>
		<td><select id="type_adresse_org">
		<?php echo $this->option_type_adresse;?>
		</select></td>
	</tr>
	<tr>
		<td>Rue</td>
		<td><input id="rue_org" type="text" /></td>
	</tr>
	<tr>
		<td>Adresse ligne 2</td>
		<th align="left" colspan="3"><input size="72" id="adresse_ligne_2_org"
			type="text" /></th>
	</tr>
	<tr>
		<td>Adresse ligne 3</td>
		<th align="left" colspan="3"><input size="72" id="adresse_ligne_3_org"
			" type="text" /></th>
	</tr>
	<tr>
		<td>Cp</td>
		<td><input id="cp_box_org" type="text" /></td>
		<td>Ville</td>
		<td><input  id="ville_box_org" type="text" />
		<div class="suggestionsBox" id="suggestions" style="display: none;">
		<div class="suggestionList" id="autoSuggestionsList">&nbsp;</div>
		</div>
		</td>
	</tr>
	<tr>
		<td>Région</td>
		<td><input id="region_box_org" type="text" /></td>
		<td>Pays</td>
		<td><input id="pays_box_org" type="text" /></td>
	</tr>
	<tr>
		<td>Tel</td>
		<td><input id="tel_org" type="text" /></td>
		<td>Fax</td>
		<td><input id="fax_org" type="text" /></td>
	</tr>
	<tr>
		<td>Email</td>
		<td><input id="email_org" type="text" /></td>
		<td>Site web</td>
		<td><input id="site_web_org" type="text" /></td>
	</tr>
	<tr>
		<td>Date d'immatriculation</td>
		<td><input id="date_immat_org" type="text" /></td>
		<td>Début d'activité</td>
		<td><input id="date_debut_activite_org" type="text" /></td>
	</tr>
	<tr>
		<td>Forme juridique</td>
		<td><select id="forme_juridique_org">
		<?php echo $this->option_forme_juridique;?>
		</select></td>
		<td>Siret</td>
		<td><input id="siret_org" type="text" /></td>
	</tr>
	<tr>
		<td>Secteur d'activité</td>
		<th align="left" colspan="3"><select id="secteur_activite_org">
		<?php echo $this->option_secteur_activite;?>
		</select></th>
	</tr>
	<tr>
		<td>Dirigeant</td>
		<td><select id="dirigeant_org">
			<option></option>
			<option value="Le beneficiaire">Le beneficiaire</option>
			<option value="L'Associe">L'Associe</option>
		</select></td>
		<td>Implantation</td>
		<td><select id="implantation_org">
		<?php echo $this->option_implantation;?>
		</select></td>
	</tr>
	<tr>
		<td>Régime Imposition</td>
		<td><select id="regime_imposition_org">
		<?php echo $this->option_regime_imposition;?>
		</select></td>
		<td>Régime TVA</td>
		<td><select id="regime_tva_org">
		<?php echo $this->option_regime_tva;?>
		</select></td>
	</tr>
	<tr>
		<td>Régime Fiscal</td>
		<td><select id="regime_fiscal_org">
		<?php echo $this->option_regime_fiscal;?>
		</select></td>
		<td>Régime Social Dirigeant</td>
		<td><select id="regime_social_dirigeant_org">
		<?php echo $this->option_regime_social_dirigeant;?>
		</select></td>
	</tr>
	<tr>
		<td>Statut</td>
		<td><select id="statut_org">
			<option></option>
			<option>En cours</option>
			<option>Cree</option>
			<option>Annulee</option>
		</select></td>
	</tr>
</table>
<br />
<br />
<center>
<button onclick="Organisation.saveContact()">Enregistrer</button>
</center>
<script type="text/javascript">
$j( "button").button();
$j('#cp_box_org').autocomplete({
	source: function( request, response ) {
		$j.ajax({
			url: "index.php?page=ajaxContact&action=getVille&noTemplate=1",
			dataType: "json",
			type : "POST",
			data: {
				
				maxRows: 12,
				queryString : request.term
			},
			success: function( data ) {
				
				//console.debug(data);
			
				response( $j.map(data, function( item ) {
					
					return {
						label: item.cp +', '+ item.ville1,
						value: item.cp,
						ville: item.ville1,
						region: item.region,
						pays : item.pays,
						
					}
				}));
			}
		});
	},
	minLength: 2,
	select: function( event, ui ) {
		
		$j('#ville_box_org').val( ui.item.ville);
		$j('#region_box_org').val( ui.item.region);
		$j('#pays_box_org').val( ui.item.pays);
	
	},
	
	
});

$j('#ville_box_org').autocomplete({
	source: function( request, response ) {
		$j.ajax({
			url: "index.php?page=ajaxContact&action=getVille&noTemplate=1",
			dataType: "json",
			type : "POST",
			data: {
				
				maxRows: 12,
				queryString : request.term
			},
			success: function( data ) {
				
				//console.debug(data);
			
				response( $j.map(data, function( item ) {
					
					return {
						label: item.cp +', '+ item.ville1,
						value: item.ville1,
						ville: item.ville1,
						region: item.region,
						pays : item.pays,
						cp : item.cp,
						
					}
				}));
			}
		});
	},
	minLength: 2,
	select: function( event, ui ) {
		$j('#cp_box_org').val( ui.item.cp);
		$j('#ville_box_org').val( ui.item.ville);
		$j('#region_box_org').val( ui.item.region);
		$j('#pays_box_org').val( ui.item.pays);
	
	},
	
	
});

$j('#code_naf_').autocomplete({
	source: function( request, response ) {
		$j.ajax({
			url: "index.php?page=ajaxOrganisation&action=getCodeNaf&noTemplate=1",
			dataType: "json",
			type : "POST",
			data: {
				
				maxRows: 12,
				queryString : request.term
			},
			success: function( data ) {
				
				//console.debug(data);
			if(data!=null)
			{
				response( $j.map(data, function( item ) {
					
					return {
						label: item.intitule_long+' ('+ item.code_naf+')',
						value: item.code_naf,
						
						
					}
				}));
			}
			}
		});
	},
	minLength: 2,
	select: function( event, ui ) {
		/*$j('#cp_box_org').val( ui.item.cp);
		$j('#ville_box_org').val( ui.item.ville);
		$j('#region_box_org').val( ui.item.region);
		$j('#pays_box_org').val( ui.item.pays);
	*/
	},
	
	
});

</script>
