<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>
<div class="contenu_redac">
<br/>
<?php echo $this->render('navigation_rapide.phtml'); ?>
 <br/> 
 </div>


	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<br/><br/>
	<form method="get"><table><tr><td><input checked="checked" type="radio" value="1" name="editer" /></td><td><img style="width:30px" src="<?php echo $this->baseUrl();?>/images/pdf.jpg" /> Editer le business plan</td></tr><tr height="50px"><td><input type="submit" value="OK" class="button" /></td><td></td></tr></table>
	
	</form>
	
</div>
	

