<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>  
   <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title><?php echo $this->title; ?></title>
	<link rel="icon" href="<?php echo $this->baseUrl();?>/images/logo_apsie_bp_petit.png" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/images/logo_apsie_bp_petit.png" type="image/x-icon" />
    <link rel="stylesheet" type="text/css"  href="<?php echo $this->baseUrl();?>/css/liste_auto.css" />
     
	<link rel="stylesheet" type="text/css" media="screen"
             href="<?php echo $this->baseUrl();?>/css/global.css" />
			 <script src="http://code.jquery.com/jquery-1.4.4.js"></script>
			 	 <link rel="stylesheet" type="text/css" media="screen"
             href="<?php echo $this->baseUrl();?>/css/menu.css" />
			 <script type='text/javascript' src='<?php echo $this->baseUrl();?>/js/jquery-1.2.3.min.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl();?>/js/menu.js'></script>

<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/ckeditor/ckeditor.js"></script>
	<script src="<?php echo $this->baseUrl();?>/js/ckeditor/_samples/sample.js" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl();?>/js/general.js" type="text/javascript"></script>

<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/calendrier/calendar-blue.css" title="blue">
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/calendrier/calendar.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/calendrier/jscalendar-setup.php"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/calendrier/etemplate.js"></script>


</head>
<body>


<!-- This next call will now include any content that was generated in the
     dispatching of a controllers action (or series of actions).  -->
<?php echo $this->layout()->content ?>

<!-- if your application requires it, this would be a great place to put a
     footer for all pages. -->

<script>
function voir_div(click_b,s_menu_g){
$(click_b).click(function() {
  $(s_menu_g).slideDown('slow');
});}

function cache_div(click_h,s_menu_g){
$(click_h).click(function() {
  $(s_menu_g).slideUp();
});}

function voir_apercu(click,page)
{
$(click).click(function() {
  $(page).slideDown('slow');
});}

/*$('#click_b').click(function() {
  $('#s_menu_presentation_g').slideDown('slow');
});*/

</script>
<script type="text/javascript">
			//<![CDATA[

				CKEDITOR.replace( 'editor_office2003',
					{
						skin : 'office2003'
					});

			//]]>
			</script>
</body>
</html>
