<div class="corp">
<div style="display:none" class="zoneRecherche">
<div class="menu_gauche">
<div class="sous_menu">Recherche sur le calendrier</div>
<div class="div_menu_gauche"><div style="padding-left:10px"><input id="motRecherche2" type="text" /> <img style="cursor:pointer;" onclick="getRecherche2();" src="./images/ico/chercher.png" />  </div>
<div  style="padding-left:10px"><a onclick="getCalendar();" href="javascript:void(0);">Retour au calendrier</a></div>
</div></div>
<div class="contenu">
<div class="univers">Calendrier : Résultat de la recherche</div>
<div align="left" class="div_menu_droit"></div>
</div></div>
   <div class="calendar">

      <div id="calhead" style="padding-left:1px;padding-right:1px;">          
            <div class="cHead"><div class="ftitle">Calendrier de <select onchange="initialiserReferent(this.value)" id="calendrier_referent"><option></option>
<?php for($i=0;$i<count($this->utilisateurs);$i++)
{ echo '<option value="'.$this->utilisateurs[$i]['account_id'].'">'.$this->utilisateurs[$i]['account_lid'].'</option>';} ?></select></div>
            <div id="loadingpannel" class="ptogtitle loadicon" style="display: none;">Loading data...</div>
             <div id="errorpannel" class="ptogtitle loaderror" style="display: none;">Sorry, could not load your data, please try again later</div>
            </div>          
             
            <div id="caltoolbar" class="ctoolbar">
             
              <div  class="fbutton">
                <div><span >

                <input id="motRecherche" style="font-size:9px" type="text" >  <img style="cursor:pointer;" onclick="getRecherche();" src="./images/ico/chercher.png" />           
                </span>
            </div></div>
           
     
            <div class="btnseparator"></div>
              <div id="showtodaybtn" class="fbutton">
                <div><span onclick="dialogRechercheDispo()" >
                Recherche de disponibilité</span></div>
            </div>
              
               <div class="btnseparator"></div>
              <div id="showtodaybtn" class="fbutton">
                <div><span onclick="dialogConfirm()" >
                Confirmation d'options</span></div>
            </div>
              <div class="btnseparator"></div>
             <div id="showtodaybtn" class="fbutton">
                <div><span title='Click to back to today ' class="showtoday">
                Aujourd'hui</span></div>
            </div>
              <div class="btnseparator"></div>

            <div id="showdaybtn" class="fbutton">
                <div><span title='Day' class="showdayview">Jour</span></div>
            </div>
              <div  id="showweekbtn" class="fbutton fcurrent">
                <div><span title='Week' class="showweekview">Semaine</span></div>
            </div>
              <div  id="showmonthbtn" class="fbutton">
                <div><span title='Month' class="showmonthview">Mois</span></div>

            </div>
            
             <div class="btnseparator"></div>
            <div id="sfprevbtn" title="Prev"  class="fbutton">
              <span class="fprev"></span>

            </div>
            <div id="sfnextbtn" title="Next" class="fbutton">
                <span class="fnext"></span>
            </div>
           
            
            <div class="clear"></div>
            </div>
      </div>
      <div style="padding:1px;">

        <div class="t1 chromeColor">
            &nbsp;</div>
        <div class="t2 chromeColor">
            &nbsp;</div>
        <div id="dvCalMain" class="calmain printborder">
            <div id="gridcontainer" style="overflow-y: visible;">
            </div>
        </div>
        <div class="t2 chromeColor">

            &nbsp;</div>
        <div class="t1 chromeColor">
            &nbsp;
        </div>   
        </div>
     
  </div>
  
</div>
<div style="display:none" id="dialogConfirm"  title="Confirmation d'options">
<div align="center" style="background-color:#CCC;"><table><tr><td><select id="confirm_conseiller_id">
<option value="" >Tous les conseillers</option><?php  for($i=0;$i<count($this->utilisateurs);$i++)
{ echo '<option value="'.$this->utilisateurs[$i]['account_id'].'">'.$this->utilisateurs[$i]['account_lid'].'</option>';} ?>
</select></td>
<td><select id="confirm_id_lieu"><option value="" >Choisir un lieu</option>
<?php for($i=0;$i<count($this->lieu);$i++)
{ echo '<option value="'.$this->lieu[$i]['id_lieu'].'-'.$this->lieu[$i]['nom_lieu'].'">'.$this->lieu[$i]['nom_lieu'].'</option>';}?></select></td><td><input value="<?php echo date('d/m/Y',time() + 2*(24 * 60 * 60))?>" size="8" id="confirm_date_start" type="text" /></td><td><button onclick="getConfirm();" style="font-size:10px">Chercher</button></td></tr></table></div>
<div id="resultat_confirm"></div></div>
<div style="display:none" id="dialogDisponibilite"  title="Recherche de disponibilité">
<div style="float:left;padding:10px;" >
		
		
<table><tr><td>Nb Options</td><td><select id="nombre"><?php for($i=3;$i<=10;$i++)
		{echo "<option  value='$i'>$i</option>";}?></select></td></tr>
		<tr><td>Pour</td><td> <select id="conseiller_id">
		<?php  for($i=0;$i<count($this->utilisateurs);$i++)
{ echo '<option value="'.$this->utilisateurs[$i]['account_id'].'">'.$this->utilisateurs[$i]['account_lid'].'</option>';} ?>
		</select></td></tr>
		<tr><td>à</td><td> <select name="lieu" id="recherche_id_lieu">
		<?php for($i=0;$i<count($this->lieu);$i++)
{ echo '<option value="'.$this->lieu[$i]['id_lieu'].'-'.$this->lieu[$i]['nom_lieu'].'">'.$this->lieu[$i]['nom_lieu'].'</option>';}?>
		</select></td></tr>
<tr><td>Date/Heure de début</td><td><input value="<?php echo date('d/m/Y');?>" size="8" id="date_start" type="text" /></td></tr>
<tr><td>Durée</td><td><select id="dispo_duree" ><option value="1"  selected="selected">01:00</option></select></td></tr>
<tr><td>Plage Horaire</td><td><select id="plage1"  >
<option value="9" selected="selected" >09</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>

</select>h jusqu'à <select id="plage2"  >
<option value="9" >09</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option selected="selected"  value="17">17</option>

</select>h</tr>
<tr><td>Sur</td><td><select id="selection"><option value="1">Un jour</option><option selected="selected" value="7">Une semaine</option><option value="14">Deux semaines</option><option value="21">Trois semaines</option><option value="28">Quatre semaines</option></select></td></tr>
    <tr><tr><td>Tous les</td><td><select id="jours"><option value="Monday">Lundi</option><option  value="Tuesday">Mardi</option><option value="Wednesday">Mercredi</option><option value="Thursday">Jeudi</option><option value="Friday">Vendredi</option><option selected="selected"  value="6">Jours ouvrés</option></select></td></tr>
</table><br/><center>	<button onclick="getDispo()" style="font-size:10px;">Nouvelle recherche</button></center>
</div><div style="float:left;padding:10px;border-left:1px solid #CCC;" id="resultat_dispo"></div></div>
<div style="display:none" id="editCalendrier"  title=""><input type="hidden" id="idCal" value=""/>
<div>
<div onclick="navigationDialogCalendrier('general');" id="cal_menu_general" class="cal_menu_general_active">Général</div>
<div onclick="navigationDialogCalendrier('participant');" id="cal_menu_participant" class="cal_menu_participant">Participants ( <span id="nb_participant">0</span> )</div>
</div>
<table  class="dialog_participant" style="border:1px solid #CCC;width:580px; "><tr><td>Affiner la sélection des contacts</td><td><input id="mot_contact" type="text" /></td><td><button onclick="rechecherContact();" >Ok</button></td></tr>
<tr><td>Sélectionner les contacts à ajouter </td><td><select id="id_contact_a_lier"></select></td><td><button onclick="lierCalContact()">Ajouter</button></td></tr>
<tr><td>Sélectionner les référents à ajouter </td><td><select id="id_referent_a_lier"><option></option>
<?php for($i=0;$i<count($this->utilisateurs);$i++)
{ echo '<option value="'.$this->utilisateurs[$i]['account_id'].'-'.$this->utilisateurs[$i]['account_firstname'].'-'.$this->utilisateurs[$i]['account_lastname'].'">'.$this->utilisateurs[$i]['account_lid'].'</option>';} ?></select></td><td><button onclick="lierCalReferent()">Ajouter</button></td></tr>
<tr><td><hr style="border:1px solid #CCC"/> </td><td><hr style="border:1px solid #CCC" /></td><td><hr style="border:1px solid #CCC" /></td></tr>
<tr><td align="center"><h3>Liste des Participants</h3></td><td></td><td></td></tr>

<tbody id="liste_participant">

</tbody>
</table>
<table  class="dialog_general" style="border:1px solid #CCC ">
<tr><td>Prestataire</td><td><select id="id_prestataire">
<?php 
for($i=0;$i<count($this->prestataire);$i++)
{
	echo'<option value="'.$this->prestataire[$i]['id_prestataire'].'">'.$this->prestataire[$i]['nom'].'</option>';
}
?>
</select></td></tr>
<tr><td>Type d'évènement</td><td><select id="id_type_evenement">
<?php 
for($i=0;$i<count($this->typeEvent);$i++)
{
	echo'<option value="'.$this->typeEvent[$i]['id_type_evenement'].'">'.$this->typeEvent[$i]['nom_court'].' ( '.$this->typeEvent[$i]['nom_long'].' )</option>';
}
?>
</select></td></tr>
<tr><td>Presta</td><td><select id="id_cal_cat"><option></option>
<?php 
for($i=0;$i<count($this->calCat);$i++)
{
	echo'<option value="'.$this->calCat[$i]['id_cal_cat'].'">'.$this->calCat[$i]['cal_cat_name'].' ( '.$this->calCat[$i]['objet_dispositif'].' )</option>';
}
?>
</select></td></tr>
<tr><td>Titre</td><td><input id="CalendarTitle" size="70" type="text" value=""/></td></tr>
<tr><td>Début</td><td><input size="8" id="date1" type="text" /> <select id="heure1">
<?php 
for($i=9;$i<18;$i++)
{
	echo "<option>".$i."</option>";
}

?></select>h <select id="min1">
<option>00</option><option>30</option></select></td></tr>
<tr><td>Durée</td><td><select id="duree" ><option>00:30</option><option selected="selected">01:00</option><option >01:30</option><option >02:00</option><option >02:30</option><option >03:00</option><option >03:30</option><option >04:00</option></select></td></tr>
<tr><td>Lieu</td><td><div style="float:left"> <select id="id_lieu"><option></option>
<?php  for($i=0;$i<count($this->lieu);$i++)
{ echo '<option value="'.$this->lieu[$i]['id_lieu'].'">'.$this->lieu[$i]['nom_lieu'].'</option>';}
?></select> </div></td></tr>
<tr><td>Statut</td><td><select id="statut_cal" ><option>P</option><option>A</option><option>R</option></select></td></tr><tr><td>Description</td><td><textarea id="Description" cols="70" rows="5"></textarea></td></tr>
</table><br/><br/>
<center><button onclick="addEvent();">Enregistrer</button></center>
</div>
  <script type="text/javascript">

  var accountId=<?php echo $_SESSION['UTILISATEUR']['account_id'];?>;
 initialiserReferent("");

  function getRecherche()
  {
	  $j('.zoneRecherche').show();
	 $j('.calendar').hide();

	$j('#motRecherche2').val($j('#motRecherche').val());
	$j('.div_menu_droit').html("");
	$j.ajax({
		url : "./index.php?page=ajaxCalendrier&noTemplate=1",
		dataType : "json",
		data : {
			mot : $j('#motRecherche2').val(),
			method : "recherche"
		    
		},
		success: function(data){
			//console.debug('%o',data);
var html='<table id="myTable" cellspacing="1" class="tablesorter"><thead><tr> ';

html +='<th>Début<br/>Fin</th><th>Titre<br/>Description</th><th>Propriétaire</th><th>Emplacement</th><th>Participant</th><th></th>';

html +='</thead></tr><tbody>';
$j.each(data,function(i, obj){
;
	
	 html += "<tr><td>"+obj.DATEDEB+"<br/>"+obj.DATEFIN+"</td>";
	 html += "<td><strong>"+obj.Subject+"</strong><br/><textarea cols='60'>"+obj.Description+"</textarea></td>";
	 html += "<td>"+obj.prenom_proprietaire+" "+obj.nom_proprietaire+"</td>";
	 html += "<td>"+obj.nom_lieu+"</td>";
	 html += "<td>"+obj.prenom_referent+" "+obj.nom_referent+"</td>";
	 html += "<td><img src='./images/ico/edit.png' /></td></tr>";
});
html +="</tbody></table>";

$j('.div_menu_droit').html(html);
$j("#myTable").tablesorter({ widgets: ['zebra'] })
			 .tablesorterPager({container: $j("#pager"),positionFixed: false });
             }
	});
	
	}
  function getRecherche2()
  {
	  $j('.zoneRecherche').show();
	 $j('.calendar').hide();

	$j('#motRecherche').val($j('#motRecherche2').val());
	$j('.div_menu_droit').html("");
	$j.ajax({
		url : "./index.php?page=ajaxCalendrier&noTemplate=1",
		dataType : "json",
		data : {
			mot : $j('#motRecherche2').val(),
			method : "recherche"
		    
		},
		success: function(data){
			//console.debug('%o',data);
var html='<table id="myTable" cellspacing="1" class="tablesorter"><thead><tr> ';

html +='<th>Début<br/>Fin</th><th>Titre<br/>Description</th><th>Propriétaire</th><th>Emplacement</th><th>Participant</th><th></th>';

html +='</thead></tr><tbody>';
$j.each(data,function(i, obj){
	 html += "<tr><td>"+obj.DATEDEB+"<br/>"+obj.DATEFIN+"</td>";
	 html += "<td><strong>"+obj.Subject+"</strong><br/><textarea cols='60'>"+obj.Description+"</textarea></td>";
	 html += "<td>"+obj.prenom_proprietaire+" "+obj.nom_proprietaire+"</td>";
	 html += "<td>"+obj.nom_lieu+"</td>";
	 html += "<td>"+obj.prenom_referent+" "+obj.nom_referent+"</td>";
	 html += "<td><img src='./images/ico/edit.png' /></td></tr>";
});
html +="</tbody></table>";

$j('.div_menu_droit').html(html);
$j("#myTable").tablesorter({ widgets: ['zebra'] })
			 .tablesorterPager({container: $j("#pager"),positionFixed: false });
             }
	});
	
	}
function getCalendar()
{
	  $j('.zoneRecherche').hide();
		 $j('.calendar').show();
  $j( "#date1" ).datepicker($j.datepicker.regional[ "fr" ]);
  $j( "#date2" ).datepicker($j.datepicker.regional[ "fr" ]);
        $j(document).ready(function() {  
           var view="week";          
           
            var DATA_FEED_URL = "./index.php?page=ajaxCalendrier&noTemplate=1";
            var op = {
                view: view,
                theme:0,
                showday: new Date(),
                accountId : accountId,
                EditCmdhandler:Edit,
                DeleteCmdhandler:Delete,
                ViewCmdhandler:View,    
                onWeekOrMonthToDay:wtd,
                onBeforeRequestData: cal_beforerequest,
                onAfterRequestData: cal_afterrequest,
                onRequestDataError: cal_onerror, 
                autoload:true,
                url: DATA_FEED_URL + "&method=list",  
                quickAddUrl: DATA_FEED_URL + "&method=add", 
                quickUpdateUrl: DATA_FEED_URL + "&method=update",
                quickDeleteUrl: DATA_FEED_URL + "&method=remove"  ,
                enableDrag: false,       
            };
            var $dv = $j("#calhead");
            var _MH = document.documentElement.clientHeight;
            var dvH = $dv.height() + 2;
            op.height = _MH - dvH;
            op.eventItems =[];
           
            var p = $j("#gridcontainer").bcalendar(op).BcalGetOp();
            if (p && p.datestrshow) {
                $j("#txtdatetimeshow").text(p.datestrshow);
            }
            $j("#caltoolbar").noSelect();
            
            $j("#hdtxtshow").datepicker({ picker: "#txtdatetimeshow", showtarget: $j("#txtdatetimeshow"),
            onReturn:function(r){                          
                            var p = $j("#gridcontainer").gotoDate(r).BcalGetOp();
                            if (p && p.datestrshow) {
                                $j("#txtdatetimeshow").text(p.datestrshow);
                            }
                     } 
            });
         
        });

        setTimeout("$j('.scolltimeevent').css('height','')",500);

        console.debug($j.fn.bcalendar);
       // setTimeout("var test =  new $j.fn.bcalendar();console.debug( test);",1000);
}
function cal_beforerequest(type)
{
    var t="Chargement des données...";
    switch(type)
    {
        case 1:
            t="Chargement des données...";
            break;
        case 2:                      
        case 3:  
        case 4:    
            t="La requête est en cours...";                                   
            break;
    }
    $j("#errorpannel").hide();
    $j("#loadingpannel").html(t).show();    
}
function cal_afterrequest(type)
{
    switch(type)
    {
        case 1:
            $j("#loadingpannel").hide();
            break;
        case 2:
        case 3:
        case 4:
            $j("#loadingpannel").html("Success!");
            window.setTimeout(function(){ $j("#loadingpannel").hide();},2000);
        break;
    }              
   
}
function cal_onerror(type,data)
{
    $j("#errorpannel").show();
}
function Edit(data)
{
    
   // console.debug("%o",data);
/*   var eurl="edit.php?id={0}&start={2}&end={3}&isallday={4}&title={1}";   
    if(data)
    {
        var url = StrFormat(eurl,data);
        OpenModelWindow(url,{ width: 600, height: 400, caption:"Gestion du calendrier",onclose:function(){
           $j("#gridcontainer").reload();
        }});
    }
    */
	
	$j( "#editCalendrier" ).attr("title","Fiche évènement");
	$j( "#editCalendrier" ).dialog({height:600,width:600});
	/*$j( "#editCalendrier" ).attr("title","Fiche évènement");
	$j( "#editCalendrier" ).dialog({height:300,width:600});*/
}    
function View(data)
{
    var str = "";
    $j.each(data, function(i, item){
        str += "[" + i + "]: " + item + "\n";
    });
   // alert(str);               
}    
function Delete(data,callback)
{           
    
    $j.alerts.okButton="Ok";  
    $j.alerts.cancelButton="Annuler";  
    hiConfirm("Etes vous sûr de vouloir supprimer cet évènement", 'Confirm',function(r){ r && callback(0);});           
}
function wtd(p)
{
   if (p && p.datestrshow) {
        $j("#txtdatetimeshow").text(p.datestrshow);
    }
    $j("#caltoolbar div.fcurrent").each(function() {
        $j(this).removeClass("fcurrent");
    })
    $j("#showdaybtn").addClass("fcurrent");
}
//to show day view
$j("#showdaybtn").click(function(e) {
    //document.location.href="#day";
    $j("#caltoolbar div.fcurrent").each(function() {
        $j(this).removeClass("fcurrent");
    })
    $j(this).addClass("fcurrent");
    var p = $j("#gridcontainer").swtichView("day").BcalGetOp();
    if (p && p.datestrshow) {
        $j("#txtdatetimeshow").text(p.datestrshow);
    }
});
//to show week view
$j("#showweekbtn").click(function(e) {
    //document.location.href="#week";
    $j("#caltoolbar div.fcurrent").each(function() {
        $j(this).removeClass("fcurrent");
    })
    $j(this).addClass("fcurrent");
    var p = $j("#gridcontainer").swtichView("week").BcalGetOp();
    if (p && p.datestrshow) {
        $j("#txtdatetimeshow").text(p.datestrshow);
    }

});
//to show month view
$j("#showmonthbtn").click(function(e) {
    //document.location.href="#month";
    $j("#caltoolbar div.fcurrent").each(function() {
        $j(this).removeClass("fcurrent");
    })
    $j(this).addClass("fcurrent");
    var p = $j("#gridcontainer").swtichView("month").BcalGetOp();
    if (p && p.datestrshow) {
        $j("#txtdatetimeshow").text(p.datestrshow);
    }
});

$j("#showreflashbtn").click(function(e){
    $j("#gridcontainer").reload();
});

//Add a new event
$j("#faddbtn").click(function(e) {
    
    var url ="edit.php";
    OpenModelWindow(url,{ width: 500, height: 400, caption: "Créer un nouveau calendrier"});
});
//go to today
$j("#showtodaybtn").click(function(e) {
    var p = $j("#gridcontainer").gotoDate().BcalGetOp();
    if (p && p.datestrshow) {
        $j("#txtdatetimeshow").text(p.datestrshow);
    }


});
//previous date range
$j("#sfprevbtn").click(function(e) {
    var p = $j("#gridcontainer").previousRange().BcalGetOp();
    if (p && p.datestrshow) {
        $j("#txtdatetimeshow").text(p.datestrshow);
    }

});
//next date range
$j("#sfnextbtn").click(function(e) {
    var p = $j("#gridcontainer").nextRange().BcalGetOp();
    if (p && p.datestrshow) {
        $j("#txtdatetimeshow").text(p.datestrshow);
    }
});

    

        function addEvent()
        {
        	
    		
if($j('#idCal').val()=="")
{ var method="add";}
else
{var method="update";

}
            var strDeb = $j('#date1').val().split('/');
            var duree = $j('#duree').val().split(':');

            if((parseInt($j('#min1').val())+parseInt(duree[1])==60))
            {var addmin = 0;
                duree[0] = parseInt(duree[0])+1;
                }
            else
            {var addmin = parseInt($j('#min1').val())+parseInt(duree[1]);}
            
            var dateDebut = strDeb[1]+'/'+strDeb[0]+'/'+strDeb[2]+' '+$j('#heure1').val()+':'+$j('#min1').val();
            var dateFin = strDeb[1]+'/'+strDeb[0]+'/'+strDeb[2]+' '+(parseInt($j('#heure1').val())+parseInt(duree[0]))+':'+addmin;

        	$j.ajax({
    			url : "./index.php?page=ajaxCalendrier&noTemplate=1",
    			dataType : "json",
    			data : {
    				CalendarEndTime : dateFin ,
    				CalendarStartTime :	dateDebut,
    				CalendarTitle : $j('#CalendarTitle').val(),
    				Description : $j('#Description').val(),
    				id_lieu : $j('#id_lieu').val(),
    				id_referent : $j('#id_referent').val(),
    				id_cal_cat : $j('#id_cal_cat').val(),
    				IsAllDayEvent : 0,
    				timezone : 2,
    				idCal : $j('#idCal').val(),
    				id_type_evenement : $j('#id_type_evenement').val(),
    				id_prestataire : $j('#id_prestataire').val(),
    				statut_cal : $j('#statut_cal').val(),
    				method : method
    			    
    			},
    			success: function(data){
        			$j('#editCalendrier').dialog('close');
    				$j("#gridcontainer").reload();
    	             }
        	});
        }
function initialiserReferent(id)
{
	if(id!="")
	{$j('#calendrier_referent').val(id);}
	else
	{
$j('#calendrier_referent').val(accountId);
	}
	getCalendar();
}

function dialogRechercheDispo()
{
	 $j( "#date_start" ).datepicker($j.datepicker.regional[ "fr" ]);
	$j('#dialogDisponibilite').dialog({height:400,width:800});
}
function dialogConfirm()
{
	 $j( "#confirm_date_start" ).datepicker($j.datepicker.regional[ "fr" ]);
	$j('#dialogConfirm').dialog({height:600,width:600});
}
function getDispo()
{
	var l = $j('#recherche_id_lieu').val().split('-');

	$j.ajax({
		url : "./index.php?page=ajaxCalendrier&noTemplate=1",
		dataType : "json",
		data : {
			plage1 : $j('#plage1').val(),
			date_start : $j('#date_start').val(),
			selection : $j('#selection').val(),
			plage2 : $j('#plage2').val(),
			duree : 3600,
			conseiller_id : $j('#conseiller_id').val(),
			lieu : l[0],
			nom_lieu : l[1],
			nombre : $j('#nombre').val(),
			jours : $j('#jours').val(),
			method : "dispo"
		    
		},
		success: function(data){
			$j('#resultat_dispo').html(data);
		}
		});
	
}
function getConfirm()
{
	var l = $j('#confirm_id_lieu').val().split('-');

	$j.ajax({
		url : "./index.php?page=ajaxCalendrier&noTemplate=1",
		dataType : "json",
		data : {
			
			conseiller_id : $j('#confirm_conseiller_id').val(),
			id_lieu : l[0],
			nom_lieu : l[1],
			date_start :  $j('#confirm_date_start').val(),
			
			method : "confirm"
		    
		},
		success: function(data){
			$j('#resultat_confirm').html(data);
		}
		});
	
}
function rechecherContact()
{


	$j.ajax({
		url : "./index.php?page=ajaxContact&noTemplate=1",
		dataType : "json",
		data : {
			
			
			mot :  $j('#mot_contact').val(),
			
			action : "rechercherContact"
		    
		},
		success: function(data){
			var html;
			$j.each(data,function(i, obj){
			html +="<option value="+obj.id_ben+"-"+obj.prenom+"-"+obj.nom+">"+obj.prenom+" "+obj.nom+"</option>";	
				
			});
			$j('#id_contact_a_lier').html(html);
		}
		
		});
	
}
function lierCalContact()
{
	
	var c = $j('#id_contact_a_lier').val().split('-');
	$j.ajax({
		url : "./index.php?page=ajaxCalendrier&noTemplate=1",
		dataType : "json",
		data : {
			
			
			id_contact :  c[0],
			prenom_contact :  c[1],
			nom_contact :  c[2],
			
			method : "lierCalContact"
		    
		},
		success: function(data){
			var html="";
			var count_data = data.length;
			var compt=0;
			$j.each(data,function(i, obj){
				if(obj.NOM!=null)
				{	
		html +='<tr><td align="right"><img src="./images/ico/ico_'+obj.TYPE+'.png"/></td><td>'+obj.PRENOM+' '+obj.NOM+'</td><td><img style="cursor:pointer" onclick="deleteParticipant('+obj.ID+',\''+obj.TYPE+'\')"  src="./images/ico/croix.png"/></td></tr>';
		compt++;}
				});
			
			$j('#liste_participant').html(html);
			$j('#nb_participant').html(compt);
		}
		
		});
	
}
function lierCalReferent()
{
	var r = new Array();
	if($j('#id_referent_a_lier').val()!="")
	{var r = $j('#id_referent_a_lier').val().split('-');
	}
	else
	{
		
		r[0] = VARTEMPS['COMPTES']['ID'];
		r[1] = VARTEMPS['COMPTES']['PRENOM'];
		r[2] = VARTEMPS['COMPTES']['NOM'];
	}
		
	

	
	$j.ajax({
		url : "./index.php?page=ajaxCalendrier&noTemplate=1",
		dataType : "json",
		data : {
			
			
			id_referent :  r[0],
			prenom_referent :  r[1],
			nom_referent :  r[2],
			
			method : "lierCalReferent"
		    
		},
		success: function(data){
			var html="";
			var compt=0;
			var count_data = data.length;
			$j.each(data,function(i, obj){
				
				if(obj.NOM!=null)
				{
		html +='<tr><td align="right"><img src="./images/ico/ico_'+obj.TYPE+'.png"/></td><td>'+obj.PRENOM+' '+obj.NOM+'</td><td><img style="cursor:pointer" onclick="deleteParticipant('+obj.ID+',\''+obj.TYPE+'\')"  src="./images/ico/croix.png"/></td></tr>';
				compt++;}
				});
			$j('#liste_participant').html(html);
			$j('#nb_participant').html(compt);
		}
		
		});

	
	
}
function Check_all(state)
{
  
  var i;
  var tabInput=document.getElementsByTagName("input");
  var n=tabInput.length;
  
  for(i=0;i<n;i++)
  {
  	if(tabInput[i].type=='checkbox')
  	{
  		tabInput[i].checked=state;
  	}
  		
  }
 }

function navigationDialogCalendrier(classe_a_voir)
{
	$j('.dialog_general').hide();
	$j('.dialog_participant').hide();
	$j('#cal_menu_general').attr('class','cal_menu_general');
	$j('#cal_menu_participant').attr('class','cal_menu_participant');
	$j('.dialog_'+classe_a_voir).show('fade');
	$j('#cal_menu_'+classe_a_voir).attr('class','cal_menu_'+classe_a_voir+'_active');

}
function getParticipants(idCal)
{
	$j.ajax({
		url : "./index.php?page=ajaxCalendrier&noTemplate=1",
		dataType : "json",
		data : {
			
			idCal : idCal,
			method : "getParticipants"
		    
		},
		success: function(data){
			
			var html="";
			var compt =0;
			$j.each(data.DATA_COMPTES,function(i, obj){
				html +='<tr><td align="right"><img src="./images/ico/ico_compte.png"></td><td>'+obj.account_firstname+ ' ' +obj.account_lastname+' </td><td><img style="cursor:pointer" onclick="deleteParticipant('+obj.account_id+',\'compte\')" src="./images/ico/croix.png"></td></tr>';
			compt++;});
			
			$j.each(data.DATA_CONTACT,function(i, obj){
			if(obj.id_ben!=null)
			{
				html +='<tr><td align="right"><img src="./images/ico/ico_contact.png"></td><td>'+obj.prenom+ ' ' +obj.nom+' </td><td><img style="cursor:pointer" onclick="deleteParticipant('+obj.id_ben+',\'contact\')" src="./images/ico/croix.png"></td></tr>';
			compt++;}
			});
			
			$j('#liste_participant').html(html);
			$j('#nb_participant').html(compt);
			}
		});
	}
	function deleteParticipant(id,type)
	{
		$j.ajax({
			url : "./index.php?page=ajaxCalendrier&noTemplate=1",
			dataType : "json",
			data : {
				
				id_participant : id,
				type : type,
				method : "deleteParticipant"
			    
			},
			success: function(data){
				var html="";
				var compt=0;
				var count_data = data.length;
				$j.each(data,function(i, obj){
					
					if(obj.NOM!=null)
					{
			html +='<tr><td align="right"><img src="./images/ico/ico_'+obj.TYPE+'.png"/></td><td>'+obj.PRENOM+' '+obj.NOM+'</td><td><img style="cursor:pointer" onclick="deleteParticipant('+obj.ID+',\''+obj.TYPE+'\')"  src="./images/ico/croix.png"/></td></tr>';
					compt++;}
					});
				$j('#liste_participant').html(html);
				$j('#nb_participant').html(compt);
			}
			
		});
		
	}
    </script> 