_presta:
    pattern:  /presta/{id}
    defaults: { _controller: LeaPrestaBundle:Default:index }

lea_presta:
    resource: "@LeaPrestaBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
