<!--corps-->
<div class="contenu_redac">

	
	
    	<div class="menu_g"><table><tr><td width="32px"></td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'ventes')); ?>">Ventes</a> </td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"></td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'achats')); ?>">Achats</a></td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'fraisgeneraux')); ?>">Frais g&eacute;n&eacute;raux</a></td></tr></table></div>
        <div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'investissements')); ?>">Investissements</a></td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'amortissements')); ?>">Amortissements</a></td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'emprunts')); ?>">Emprunts</a></td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'personnel')); ?>">Personnel</a></td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'besoinfonds')); ?>">Besoin en fonds de roulement</a></td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'compteresultat')); ?>">Compte de r&eacute;sultat</a></td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'planfinancement')); ?>">Plan de financement</a></td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'tva')); ?>">T.V.A.</a></td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'tresorerie')); ?>">Tr&eacute;sorie</a></td></tr></table></div>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'tableaubord')); ?>">Tableau de bord</a></td></tr></table></div>
		<br/><br/>
		<div class="menu_g"><table><tr><td width="32px"> </td><td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'home')); ?>"> << Retour accueil </a></td></tr></table></div>
</div>
 
    


<!--fin_corps-->

