<!--corps-->
<div class="contenu_redac">

	
	
    	<div class="menu_g"><table><tr><td width="32px"></td><td><a href="<?php echo $this->url(array('controller'=>'redaction','action'=>'sommaire')); ?>">Redaction</a></td></tr></table></div>
	<?php /*	<div class="menu_g"><table><tr><td width="32px"></td><td><a href="<?php echo $this->url(array('controller'=>'financier','action'=>'introduction')); ?>">Dossier financier</a></td></tr></table></div>
		*/ ?>
  </div>

 
    


<!--fin_corps-->