<a name="haut_page"><?php echo $this->render('header.phtml'); ?></a>


<div class="intitule_dossier"><img src="<?php echo $this->baseUrl();?>/images/titre_business2.png" /> Business plan de <?php echo $this->nom_complet; ?><br/><img src="<?php echo $this->baseUrl();?>/images/Briefcase-32.png" /> Projet : <?php echo $this->desc_projet; ?>
</div>
<div class="contenu_redac">
<br/>
<?php echo $this->render('navigation_rapide.phtml'); ?>
</div>
	<div class="contenu_ac">
	<div><?php echo $this->title; ?></div><br/><br/>
<div class="titre_long">Exemple de business plan</div>
	<div>
<br/>
	
	<ul><li> <img style="width:30px" src="<?php echo $this->baseUrl();?>/images/word.gif" /> <a href="<?php echo $this->baseUrl(); ?>/doc/starlight.doc" >Starlight</a></li></ul>
<br/><br/>

	
</div>