<div class="corp">
<div class="menu_gauche">
<div class="sous_menu"><br/></div>
<div class="div_menu_gauche">

<table><tr><td>Porteur de projet </td><td> : <strong>Ahmed Timsit</strong></td></tr>
<tr><td>Développeur Informatique </td><td> : <strong>Dolyveen Renault</strong> </td></tr></table>
</div></div>
<div style="text-align:left" class="contenu">
<div class="univers">Acceuil</div>
<div style="padding-left:10px"  class="div_menu_droit"><span class="titreVersion">Extranet v2.0</span> <br/><span>Mise à jours le 10/08/2011 par <i>drenault</i></span>
<h3>Presta 2.0</h3>
<ul>
<li>Affichage des prestations actifs ( dispositif )</li>
<li>Intégration des graphiques cliquables de type camemberts</li>
<li>Chaque statut de prestation correpond à un code couleur</li>
<li>Zone de recherche permet d'afficher les graphiques en fonction du mot saisie</li>
<li>Reprise de Presta 1.0 pour les livrables ( ECPE, NACRE )</li>
</ul>
<h3>Contact 2.0</h3>
<ul>
<li>Possibilité de sélectionner les champs à afficher</li>
<li>Possibilité de ssauvegarder vos paramètres pour une prochaine utilisation</li>
<li>Affichage des données dans un tableau triable de façon ergonomique</li>
<li>Création / modification d'un contact</li>
<li>Recherche multiple avec le séparateur ";"</li>
<li>Export excel des données</li>
</ul>
<h3>Calendrier 2.0</h3>
<ul>
<li>Reprise du calendrier 1.0</li>
<li>Ajout du champs type d'évènement</li>
<li>Ajout du champs presta</li>
<li>Ajout du champs lieu</li>
<li>Possibilité d'ajouter plusieurs participants dont les contacts en base de donnée</li>
</ul>

<h3>Projet 2.0</h3>
<h3>Evenement 2.0</h3>
<h3>Dispositif 2.0</h3>
</div>
</div></div>