<div class="corp">
<div class="menu_gauche">
<div class="sous_menu">Recherche avancée</div>
<div class="div_menu_gauche">
<div class="lien_recherche"><div ></div></div>
<div id="filtre"  style="display:block" class="option_recherche">

<table><tr><td>Dispositif</td><td><select id="etat" onchange="Dispositif.getDispositif();" ><option value="" >Tous</option><option value="1">Actif</option><option value="0">Inactif</option></select></td></tr></table>


 </div>

</div>
</div>
<div class="contenu">
<div class="univers">Dispositif</div>
<div class="div_menu_droit">

<div class="boutton_contact"><button onclick="Dispositif.addDispositifBox();"  style="font-size:10px">Créer un nouveau dispositif</button></div><div class="page"></div><div  class="contenu_flex">
</div>

</div></div></div>

<div style="display:none" id="editParametre"  title="">
<table><tr><td>Libellé du paramètre</td><td><input id="idParametre" type="hidden" value=""/><input type="text" id="libelleParametre"  value=""/></td><td></td><td><button onclick="updateParametre()" >Enregistrer</button></td></tr></table>
</div>
<div style="display:none" id="saveParametre"  title="Sauvegarde des paramètres">
<table><tr><td>Sauvegardes existantes</td><td><select id="selectParam"><option></option>
<?php for($i=0;$i<count($this->param);$i++)
{
echo'<option value="'.$this->param[$i]['id_parametre'].'">'.utf8_encode($this->param[$i]['libelle_parametre']).'</option>';
}?>
</select></td></tr>
<tr><td>ou</td><td></td></tr>
<tr><td>Nouvelle sauvegarde</td><td><input id="inputParam" type="text" /></td></tr>
<tr><td></td><td><button onclick="saveParametre2()" >Enregistrer</button></td></tr>
</table>
<div style="color:green;padding:5px;" class="retour_param"></div>
</div>

<div style="display:none" id="dispositif_box"  title="">
<table>
<tr><td>Nom du dispositif</td><td><input id="id_dispositif"  type="hidden" /> <input id="nom_dispositif"  type="text" /></td></tr>
<tr><td>Numéro de marché</td><td><input id="numero_marche" type="text" /></td></tr>
<tr><td>Objet</td><td><input id="objet_dispositif"  type="text" /></td></tr>
<tr><td>Date de début</td><td><input id="date_debut_dispositif" type="text" /></td></tr>
<tr><td>Date de fin</td><td><input id="date_fin_dispositif" type="text" /></td></tr>
<tr><td>Etat</td><td><select id="is_active"><option value="1">Actif</option><option value="0">Inactif</option></select></td></tr>
</table>
<center><button onclick="Dispositif.addDispositif();" >Enregistrer</button></center>
</div>

<script type="text/javascript">

$j("button").button();
$j( "#date_debut_dispositif" ).datepicker($j.datepicker.regional[ "fr" ]);
$j( "#date_fin_dispositif" ).datepicker($j.datepicker.regional[ "fr" ]);

$j('#buttonRelancer').click(function() {
	  Dispositif.getDispositif();
	});

Dispositif.getDispositif();

</script>
