<!--corps-->
<div class="contenu_redac">
<br/>
<?php echo $this->render('navigation_rapide.phtml'); ?>
 <br/>  		
<div class="titre_outils">Menu : LE PROJET</div>        
       
        <div class="menu_g"><table><tr><td >1. <a onclick="accordeon('div_1')"><?php echo $this->titreProjet->titre_1; ?> </a></td></tr></table>
        </div>
        

            <div id="div_1" class="s_menu_g" style="display:none">
				<div>1.1.<a href="<?php  echo $this->baseUrl();?>/redaction/titreprojet11/?div=div_1" ><?php echo $this->titreProjet->titre_1_1; ?></a></div>
				<div>1.2.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet12/?div=div_1" ><?php echo $this->titreProjet->titre_1_2; ?></a></div>
				<div>1.3.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet13/?div=div_1" ><?php echo $this->titreProjet->titre_1_3; ?></a></div>
				<div>1.4.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet14/?div=div_1" ><?php echo $this->titreProjet->titre_1_4; ?></a></div>
				<div>1.5.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet15/?div=div_1" ><?php echo $this->titreProjet->titre_1_5; ?></a></div>
				<div>1.6.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet16/?div=div_1" ><?php echo $this->titreProjet->titre_1_6; ?></a></div>
	</div>
            
            
           
  		<div class="menu_g"><table><tr><td>2. <a onclick="accordeon('div_2')"><?php echo $this->titreProjet->titre_2; ?></a></td></tr></table>
        </div>
        
   
 			<div id="div_2" class="s_menu_g" style="display:none">	
 				<div>2.1.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet21/?div=div_2" ><?php echo $this->titreProjet->titre_2_1; ?></a></div>
				<div>2.2.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet22/?div=div_2" ><?php echo $this->titreProjet->titre_2_2; ?></a></div>
				<div>2.3.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet23/?div=div_2" ><?php echo $this->titreProjet->titre_2_3; ?></a></div>	
				<div>2.4.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet24/?div=div_2" ><?php echo $this->titreProjet->titre_2_4; ?></a></div>	
							
			</div> 
		
		<div class="menu_g"><table><tr><td>3. <a onclick="accordeon('div_3')"><?php echo $this->titreProjet->titre_3; ?></a></td></tr></table>
        </div>	   
			<div id="div_3" class="s_menu_g" style="display:none">	
 				<div>3.1.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet31/?div=div_3" ><?php echo $this->titreProjet->titre_3_1; ?></a></div>
				<div>3.2.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet32/?div=div_3" ><?php echo $this->titreProjet->titre_3_2; ?></a></div>
				<div>3.3.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet33/?div=div_3" ><?php echo $this->titreProjet->titre_3_3; ?></a></div>
				<div>3.4.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet34/?div=div_3" ><?php echo $this->titreProjet->titre_3_4; ?></a></div>
				<div>3.5.<a  href="<?php  echo $this->baseUrl();?>/redaction/titreprojet35/?div=div_3" ><?php echo $this->titreProjet->titre_3_5; ?></a></div>
	
							
			</div>     
</div>

<script>

function accordeon(div)
{
	if($('#'+div).attr('alt')=="Ouvert")
	{$('#'+div).hide('highlight');
	$('#'+div).attr('alt','Fermer');
	}
	else
	{$('#'+div).show('highlight');
	$('#'+div).attr('alt','Ouvert');
	}


}

</script>
<?php 
		if(isset($_GET['div']) or isset($_GET['div']))
		{
		echo'<script>accordeon("'.$_GET['div'].'")</script>';
		
		}
		?>