<!--corps-->
<div class="contenu_redac">
<br/>
<?php echo $this->render('navigation_rapide.phtml'); ?>
 <br/>  		
<div class="titre_outils">Menu : ASPECTS JURIDIQUES, FISCAUX et SOCIAUX</div>        
       
        <div class="menu_g"><table><tr><td ><a  href="<?php  echo $this->baseUrl();?>/redaction/titreaspect1/">1. LES ASPECTS JURIDIQUES</a></td></tr></table>
        </div>
        

        	
            
            
           
  		<div class="menu_g"><table><tr><td><a href="<?php  echo $this->baseUrl();?>/redaction/titreaspect2/">2. LES ASPECTS FISCAUX</a></td></tr></table>
        </div>
        
   <div class="menu_g"><table><tr><td><a href="<?php  echo $this->baseUrl();?>/redaction/titreaspect3/">3. LES ASPECTS SOCIAUX</a></td></tr></table>
        </div>
 			
</div>

