<div class="titre_outils">Navigation rapide</div> 
<br/>
<div class="navigation_rapide">
	<div><img src="<?php echo $this->baseUrl();?>/images/home.png" /> <a href="<?php echo $this->baseUrl();?>/index/home/">Accueil</a></div>
	<div><img src="<?php echo $this->baseUrl();?>/images/user_little.png" /> <a href="<?php echo $this->baseUrl();?>/redaction/sommairepresentation/">Presentation du porteur de projet</a></div>
	<div><img  src="<?php echo $this->baseUrl();?>/images/projet_little.png" /> <a href="<?php echo $this->baseUrl();?>/redaction/sommaireprojet/">Le projet</a></div>
	<div><img  src="<?php echo $this->baseUrl();?>/images/aspect.png" /> <a href="<?php echo $this->baseUrl();?>/redaction/sommaireaspect/">Les aspects juridiques, fiscaux, sociaux</a></div>
	<div><img  src="<?php echo $this->baseUrl();?>/images/logo_apsie_bp_petit.png" /> <a href="<?php echo $this->baseUrl();?>/redaction/sommairefinancier/">Le dossier financier</a></div>
	<div><img  src="<?php echo $this->baseUrl();?>/images/pdf_little.png" /> <a href="<?php echo $this->baseUrl();?>/impression/edition/">Edition</a></div>
</div>	