<?php
/**
	* eGroupWare - eTemplates for Application spiref
	* http://www.egroupware.org
	* generated by soetemplate::dump4setup() 2012-07-04 16:50
	*
	* @license http://opensource.org/licenses/gpl-license.php GPL - GNU General Public License
	* @package spiref
	* @subpackage setup
	* @version $Id: class.soetemplate.inc.php 38822 2012-04-05 12:45:00Z ralfbecker $
	*/

$templ_version=1;

