<?php

namespace Lea\PrestaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EgwAddressbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgwAddressbookRepository extends EntityRepository
{
	public function getContacts($catId = null, $idOrganisation = null, $string = null, $idBen = null) {
        $dqlPlus = null;
        // if ($catId != null)
        //     $dqlPlus .= " and c.catId ='" . $catId . "'";

        if ($idOrganisation != null){
            $dqlPlus .= " and ((l.app1 = 'addressbook' and l.app2 = 'spiclient' and l.id2 ='" . $idOrganisation . "') or (l.app2 = 'addressbook' and l.app1 = 'spiclient' and l.id1 ='" . $idOrganisation . "'))";
        }


        if ($idBen != null)
            $dqlPlus .= " and c.contactId =" . $idBen . " ";

        $dql = "	SELECT c
					FROM LeaPrestaBundle:EgwAddressbook c
					JOIN LeaPrestaBundle:EgwLink l
					where 
					(c.nFamily like :key or c.nGiven like :key or c.nFn like :key)
					" . $dqlPlus . "
        			";

        // die($dql);
        return $this->getEntityManager()
                        ->createQuery($dql)
                        ->setParameter('key', '' . $string . '%')
                        ->getResult();
    }

    public function lastId() {

        return $this->createQueryBuilder('c')
                        ->orderBy('c.contactId', 'DESC')
                        ->setMaxResults(1)
                        ->getQuery()
                        ->getSingleResult();
    }

    public function update($doctrine, $params, $user) {
        $em = $doctrine->getManager();
        # Vérification si le contacte existe déja
        if ($params['EgwAddressbook']['contactId'] != null)
            $c = $doctrine->getRepository('LeaPrestaBundle:EgwAddressbook')->find($params['EgwAddressbook']['contactId']);
        else
            $c = null;

        if ($c == true && $c != null) {
            //$c = $c[0];
            $c->setIdModifier($user->getAccountId()->getAccountId());
            $c->setDateLastModified(time());
            $c->setNom($params['EgwAddressbook']['nFamily']);
            $c->setnGiven($params['EgwAddressbook']['nGiven']);
            $c->setNomJeuneFille($params['EgwAddressbook']['nomJeuneFille']);
            $c->setDeuxiemenGiven($params['EgwAddressbook']['deuxiemenGiven']);
            $c->setCivilite($params['EgwAddressbook']['civilite']);
            $c->setnFn($params['EgwAddressbook']['civilite'] . ' ' . $params['EgwAddressbook']['nGiven'] . ' ' . $params['EgwAddressbook']['nFamily']);
            $c->setPortablePerso($params['EgwAddressbook']['portablePerso']);
            $c->setPortablePro($params['EgwAddressbook']['portablePro']);
            $c->setTelDomicile1($params['EgwAddressbook']['telDomicile1']);
            $c->setTelDomicile1($params['EgwAddressbook']['telDomicile2']);
            $c->setTelPro1($params['EgwAddressbook']['telPro1']);
            $c->setTelPro2($params['EgwAddressbook']['telPro2']);
            $c->setTelPro2($params['EgwAddressbook']['telPro2']);
            $c->setFaxPerso($params['EgwAddressbook']['faxPerso']);
            $c->setFaxPro($params['EgwAddressbook']['faxPro']);
            $c->setService($params['EgwAddressbook']['service']);
            $c->setFonction($params['EgwAddressbook']['fonction']);
            $c->setAdresseLigne1($params['EgwAddressbook']['adresseLigne1']);
            $c->setAdresseLigne2($params['EgwAddressbook']['adresseLigne2']);
            $c->setAdresseLigne3($params['EgwAddressbook']['adresseLigne3']);
            $c->setVille($params['EgwAddressbook']['ville']);
            $c->setRegion($params['EgwAddressbook']['region']);
            $c->setCp($params['EgwAddressbook']['cp']);
            $c->setPays($params['EgwAddressbook']['pays']);
            $c->setSitePerso($params['EgwAddressbook']['sitePerso']);
            $c->setEmailPerso($params['EgwAddressbook']['emailPerso']);
            $c->setEmailPro($params['EgwAddressbook']['emailPro']);
        } else {
            $c = new EgwAddressbook();
            #to-do
            $c->setCatId(327);
            $c->setIdOwner($user->getAccountId()->getAccountId());
            $c->setDateCreation(time());
            $c->setIdModifier($user->getAccountId()->getAccountId());
            $c->setDateLastModified(time());
            $c->setNom($params['EgwAddressbook']['nFamily']);
            $c->setnGiven($params['EgwAddressbook']['nGiven']);
            $c->setNomJeuneFille($params['EgwAddressbook']['nomJeuneFille']);
            $c->setDeuxiemenGiven($params['EgwAddressbook']['deuxiemenGiven']);
            $c->setCivilite($params['EgwAddressbook']['civilite']);
            $c->setnFn($params['EgwAddressbook']['civilite'] . ' ' . $params['EgwAddressbook']['nGiven'] . ' ' . $params['EgwAddressbook']['nFamily']);
            $c->setPortablePerso($params['EgwAddressbook']['portablePerso']);
            $c->setTelDomicile1($params['EgwAddressbook']['telDomicile1']);
            $c->setEmailPerso($params['EgwAddressbook']['emailPerso']);
            $c->setEmailPro($params['EgwAddressbook']['emailPro']);
            $c->setIdOrganisation('');
            $c->setOrganisation('');
            $c->setService('');
            $c->setFonction('');
            $c->setAdresseLigne1('');
            $c->setAdresseLigne2('');
            $c->setAdresseLigne3('');
            $c->setVille('');
            $c->setRegion('');
            $c->setCp('');
            $c->setPays('');
            $c->setTelPro1('');
            $c->setTelPro2('');
            $c->setTelDomicile2('');
            $c->setFaxPro('');
            $c->setFaxPerso('');
            $c->setPortablePro('');
            $c->setSitePerso('');
        }





        $em->persist($c);
        $em->flush();


        //$c_ =  $doctrine->getRepository('LeaPrestaBundle:EgwAddressbook')->lastId();

        $cParcours = $doctrine->getRepository('LeaPrestaBundle:EgwAddressbookParcoursPro')->findBy(array('contactId' => $c->getIdBen()));

        $cParcours[0]->setStatut($params['EgwAddressbookParcoursPro']['statut']);
        $cParcours[0]->setIdentifiant($params['EgwAddressbookParcoursPro']['identifiant']);
        $cParcours[0]->setDateLastModified(time());

        $em->persist($cParcours[0]);
        $em->flush();

        #Sauvegarde de la description du projet  
        // if ($params['EgwProjet'] != null) {
        //     $projet = $doctrine->getRepository('LeaPrestaBundle:EgwProjet')->findByIdBen($c->getIdBen());
        //     $projet[0]->setDescriptionProjet($params['EgwProjet']['description_projet']);
        //     $em->persist($projet[0]);
        //     $em->flush();
        //     unset($projet);
        // }
        // unset($c);
        // unset($cParcours);
    }
}
