<?php

namespace Lea\PrestaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 *  EgwAccountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgwAccountsRepository extends EntityRepository
{
	
		
		public function getAccounts($account_id = null)
		{
			if($account_id!=null && is_numeric($account_id))
			$sqlPlus=" and c.accountId=".$account_id." ";
			else
			$sqlPlus=null;
			
			$dql="	SELECT c,a FROM LeaPrestaBundle:EgwAccounts c
					JOIN c.accountId a
					where c.accountType = 'u'
        			and c.accountStatus = 'A'
        			and (c.accountPrimaryGroup =-3007
        			or c.accountPrimaryGroup =-9
					or c.accountPrimaryGroup =-2)
        			".$sqlPlus."
        			order by a.nFn asc
        			";
			// spirea - tch - ajout du groupe -2 
			// la gestion des groupes est en dur !!
			
			return $this->getEntityManager()
					->createQuery($dql)
					->getResult();
		}
	
}
