<?php

namespace Lea\PrestaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EgwContactPrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgwContactPrRepository extends EntityRepository {

    public function getPrescripteurs($catId = null, $idOrganisation = null, $string = null, $idBen = null) {
        $dqlPlus = null;
        if ($catId != null)
            $dqlPlus .= " and c.catId ='" . $catId . "'";

        if ($idOrganisation != null){
            // $dqlPlus .= " and ((l.app1 = 'addressbook' and l.app2 = 'spiclient' and l.id2 ='" . $idOrganisation . "') or (l.app2 = 'addressbook' and l.app1 = 'spiclient' and l.id1 ='" . $idOrganisation . "'))";
        }


        if ($idBen != null)
            $dqlPlus .= " and c.idBen =" . $idBen . " ";

        $dql = "	SELECT c
					FROM LeaPrestaBundle:EgwContact c
					where 
					(c.nom like :key or c.prenom like :key or c.nomComplet like :key)
					" . $dqlPlus . "
        			";

        // die($dql);
        return $this->getEntityManager()
                        ->createQuery($dql)
                        ->setParameter('key', '' . $string . '%')
                        ->getResult();
    }

    public function lastId() {

        return $this->createQueryBuilder('c')
                        ->orderBy('c.idBen', 'DESC')
                        ->setMaxResults(1)
                        ->getQuery()
                        ->getSingleResult();
    }

    public function update($doctrine, $params, $user) {
        $em = $doctrine->getManager();
        # Vérification si le contacte existe déja
        if ($params['EgwContact']['idBen'] != null)
            $c = $doctrine->getRepository('LeaPrestaBundle:EgwContact')->find($params['EgwContact']['idBen']);
        else
            $c = null;

        if ($c == true && $c != null) {
            //$c = $c[0];
            $c->setIdModifier($user->getAccountId()->getAccountId());
            $c->setDateLastModified(time());
            $c->setNom($params['EgwContact']['nom']);
            $c->setPreNom($params['EgwContact']['prenom']);
            $c->setNomJeuneFille($params['EgwContact']['nomJeuneFille']);
            $c->setDeuxiemePrenom($params['EgwContact']['deuxiemePrenom']);
            $c->setCivilite($params['EgwContact']['civilite']);
            $c->setNomComplet($params['EgwContact']['civilite'] . ' ' . $params['EgwContact']['prenom'] . ' ' . $params['EgwContact']['nom']);
            $c->setPortablePerso($params['EgwContact']['portablePerso']);
            $c->setPortablePro($params['EgwContact']['portablePro']);
            $c->setTelDomicile1($params['EgwContact']['telDomicile1']);
            $c->setTelDomicile1($params['EgwContact']['telDomicile2']);
            $c->setTelPro1($params['EgwContact']['telPro1']);
            $c->setTelPro2($params['EgwContact']['telPro2']);
            $c->setTelPro2($params['EgwContact']['telPro2']);
            $c->setFaxPerso($params['EgwContact']['faxPerso']);
            $c->setFaxPro($params['EgwContact']['faxPro']);
            $c->setService($params['EgwContact']['service']);
            $c->setFonction($params['EgwContact']['fonction']);
            $c->setAdresseLigne1($params['EgwContact']['adresseLigne1']);
            $c->setAdresseLigne2($params['EgwContact']['adresseLigne2']);
            $c->setAdresseLigne3($params['EgwContact']['adresseLigne3']);
            $c->setVille($params['EgwContact']['ville']);
            $c->setRegion($params['EgwContact']['region']);
            $c->setCp($params['EgwContact']['cp']);
            $c->setPays($params['EgwContact']['pays']);
            $c->setSitePerso($params['EgwContact']['sitePerso']);
            $c->setEmailPerso($params['EgwContact']['emailPerso']);
            $c->setEmailPro($params['EgwContact']['emailPro']);
        } else {
            $c = new EgwContact();
            #to-do
            $c->setCatId(327);
            $c->setIdOwner($user->getAccountId()->getAccountId());
            $c->setDateCreation(time());
            $c->setIdModifier($user->getAccountId()->getAccountId());
            $c->setDateLastModified(time());
            $c->setNom($params['EgwContact']['nom']);
            $c->setPreNom($params['EgwContact']['prenom']);
            $c->setNomJeuneFille($params['EgwContact']['nomJeuneFille']);
            $c->setDeuxiemePrenom($params['EgwContact']['deuxiemePrenom']);
            $c->setCivilite($params['EgwContact']['civilite']);
            $c->setNomComplet($params['EgwContact']['civilite'] . ' ' . $params['EgwContact']['prenom'] . ' ' . $params['EgwContact']['nom']);
            $c->setPortablePerso($params['EgwContact']['portablePerso']);
            $c->setTelDomicile1($params['EgwContact']['telDomicile1']);
            $c->setEmailPerso($params['EgwContact']['emailPerso']);
            $c->setEmailPro($params['EgwContact']['emailPro']);
            $c->setIdOrganisation('');
            $c->setOrganisation('');
            $c->setService('');
            $c->setFonction('');
            $c->setAdresseLigne1('');
            $c->setAdresseLigne2('');
            $c->setAdresseLigne3('');
            $c->setVille('');
            $c->setRegion('');
            $c->setCp('');
            $c->setPays('');
            $c->setTelPro1('');
            $c->setTelPro2('');
            $c->setTelDomicile2('');
            $c->setFaxPro('');
            $c->setFaxPerso('');
            $c->setPortablePro('');
            $c->setSitePerso('');
        }





        $em->persist($c);
        $em->flush();


        //$c_ =  $doctrine->getRepository('LeaPrestaBundle:EgwContact')->lastId();

        $cParcours = $doctrine->getRepository('LeaPrestaBundle:EgwContactParcoursPro')->findBy(array('idBen' => $c->getIdBen()));

        $cParcours[0]->setStatut($params['EgwContactParcoursPro']['statut']);
        $cParcours[0]->setIdentifiant($params['EgwContactParcoursPro']['identifiant']);
        $cParcours[0]->setDateLastModified(time());

        $em->persist($cParcours[0]);
        $em->flush();


	// 23/07/2018
        $cFormation = $doctrine->getRepository('LeaPrestaBundle:EgwContactFormation')->findBy(array('idBen' => $c->getIdBen()));

        /*$cFormation[0]->setNiveauFormation($params['EgwContactFormation']['niveauFormation']);
        $cFormation[0]->setIntituleFormation($params['EgwContactFormation']['intituleFormation']);
        $cFormation[0]->setDateLastModified(time());

        $em->persist($cFormation[0]);
        $em->flush();*/




        #Sauvegarde de la description du projet  
        if ($params['EgwProjet'] != null) {
            $projet = $doctrine->getRepository('LeaPrestaBundle:EgwProjet')->findByIdBen($c->getIdBen());
            $projet[0]->setDescriptionProjet($params['EgwProjet']['description_projet']);
            $em->persist($projet[0]);
            $em->flush();
            unset($projet);
        }
        unset($c);
        unset($cParcours);
    }

}
