<?php

namespace Lea\PrestaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EgwEpceTexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgwEpceTexteRepository extends EntityRepository
{
	
		
		public function get($statut)
		{
			
			
			$dql="SELECT c FROM LeaPrestaBundle:EgwEpceTexte c where c.intitule ='".$statut."' order by c.valeur asc";
			
			//die($dql);
			return $this->getEntityManager()
					->createQuery($dql)
					
					->getResult();
		}
		
	

	
}
