<?php

namespace Lea\PrestaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Lea\PrestaBundle\Models\Outils;

/**
 *  EgwOrganisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgwOrganisationRepository extends EntityRepository
{
	
		
		public function getOrganisation($catId = null,$string)
		{
			/*if($catId!=null && is_numeric($account_id))
			$sqlPlus=" and c.accountId=".$account_id." ";
			else
			$sqlPlus=null;*/
			
			$dql="	SELECT o FROM LeaPrestaBundle:EgwOrganisation o
					where o.type = 1 and (o.nomOrganisme like '%".Outils::supCaractere($string)."%'
					or o.codeOrg like '".$string."%')
        			order by o.nomOrganisme asc
        			";
			
			return $this->getEntityManager()
					->createQuery($dql)
					->getResult();
		}

		public function lastId()
		{
			
			return $this->createQueryBuilder('c')
						->orderBy('c.idOrganisation', 'DESC')
						->setMaxResults(1)
						->getQuery()
						->getSingleResult();
			
		}
}
