<?php

namespace Lea\PrestaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 *  EgwProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgwProjetRepository extends EntityRepository
{
	
		
		
		
	public function lastId()
		{
			
			return $this->createQueryBuilder('p')
						->orderBy('p.idProjet', 'DESC')
						->setMaxResults(1)
						->getQuery()
						->getSingleResult();
			
		}
	
}
