<?php

namespace Lea\PrestaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 *  EgwPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgwPrestationRepository extends EntityRepository{	
	public function lastId(){
		return $this->createQueryBuilder('p')
					->orderBy('p.idPresta', 'DESC')
					->setMaxResults(1)
					->getQuery()
					->getSingleResult();	
	}
		
	public function get($statut = null,$account_id = null,$idTypePresta = null,$libelle = null, $champDate = null, $dateDebut = null, $dateFin = null, $idPrestation = null){
		// echo 'Statut: '.$statut.'<br>';
		// echo 'Account: '.$account_id.'<br>';
		// echo 'Type: '.$idTypePresta.'<br>';
		// echo 'Libelle: '.$libelle.'<br>';
		// echo 'Champ date: '.$champDate.'<br>';
		// echo 'Date debut: '.$dateDebut.'<br>';
		// echo 'Date fin: '.$dateFin.'<br>';
		
		$sqlPlus = null;
		
		if($statut!=null) $sqlPlus .=" where p.statut = '".$statut."' ";

		if($account_id!=null){
			if($sqlPlus == null)
				$clause = "where";
			else 
				$clause ="and";

			$sqlPlus .=" ".$clause." p.idRef = ".$account_id." ";
		}
				
		if($idTypePresta!=null){
			if($sqlPlus == null)
				$clause = "where";
			else 
				$clause ="and";

			$sqlPlus .=" ".$clause." p.dispositif = ".$idTypePresta." ";
		}
				
		if($idPrestation!=null){
			if($sqlPlus == null)
				$clause = "where";
			else 
				$clause ="and";
				
			$sqlPlus .=" ".$clause." p.idPresta = ".$idPrestation." ";
		}
				
		if($libelle!=null){
			if($sqlPlus == null)
				$clause = "where";
			else 
				$clause ="and";
					
			$sqlPlus .=" ".$clause." p.intitule like '%".$libelle."%' or p.lettreDeCommande like '%".$libelle."%'";
		}

		if($champDate!=null){
			if($sqlPlus == null)
				$clause = "where";
			else 
				$clause ="and";

			if($dateDebut!=null or $dateFin!=null){
				if($dateDebut!=null){
					$dateDebut = strtotime(str_replace("/", "-", $dateDebut));
					$filter[] = "p.".$champDate." > '".$dateDebut."'";
				}
				if($dateFin!=null){
					$dateFin = strtotime(str_replace("/", "-", $dateFin)) + 86400;
					$filter[] = "p.".$champDate." < '".$dateFin."'";
				}

				$sqlPlus .=" ".$clause." ".implode(" and ", $filter);
			}
		}
			
		$dql="	SELECT p,pr,ac,t
		FROM LeaPrestaBundle:EgwPrestation p
		inner join p.prestataire pr
		left join p.account ac
		left join p.dispositif t				
		".$sqlPlus."
		order by p.dateDebut desc";
			
		// echo $this->getEntityManager()->createQuery($dql)->getSQL();

		return $this->getEntityManager()
					->createQuery($dql)	
					->getResult();
	}
}
